---
title: "Regresion Lineal"
author: "Javier Ramirez Cospin"
date: "18/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Instalacion de librerias
``` {r }
install.packages("ggplot2")
install.packages("broom")
install.packages("ggpubr")
```
### Carga de librerias
``` {r }
library(plyr)
library(dplyr)
library('cluster')
library('e1071')
library('mclust')
library('fpc')
library('NbClust')
library('factoextra')
library('tidyverse')
library('readr')
library('ppclust')
library(randomForest)
library(ggplot2)
library(broom)
library(ggpubr)
library(corrplot)
```
### Cargar y Limpiar Datos
``` {r }
rawData <- read.csv("train.csv",TRUE,",")
datos <- read.csv("train.csv",TRUE,",")
rawData[is.na(rawData)] = "NO"
datos[is.na(datos)] = "NO"
datos <- select(datos,LotArea,TotalBsmtSF,X1stFlrSF,X2ndFlrSF,WoodDeckSF,OpenPorchSF,
                EnclosedPorch,X3SsnPorch,ScreenPorch,PoolArea,MiscVal,SalePrice)
scaledData <- as.matrix(scale(datos))
```
### Aplicacion de Clusters a los datos
``` {r }
km<-kmeans(scaledData, 3, iter.max = 100)
fviz_cluster(km, data = scaledData, frame.type = "convex")
```
### Aplicacion de clusters a datos
``` {r }
set.seed(12345)
rawData$Group <- km$cluster
head(rawData)
```
### Separacion de Grupos de entrenamiento y prueba
``` {r }
trainGroup <- rawData[sample(1:nrow(rawData),nrow(rawData)*0.7,),]
testGroup <- rawData[sample(1:nrow(rawData),nrow(rawData)*0.3,),]
set.seed(123)
```
### Correlacion entre variables
``` {r }
correlation <- cor(select(trainGroup,LotArea,TotalBsmtSF,X1stFlrSF,X2ndFlrSF,WoodDeckSF,OpenPorchSF,
                EnclosedPorch,X3SsnPorch,ScreenPorch,PoolArea,MiscVal,SalePrice))
linearRegression.lm <- lm(SalePrice ~ LotArea+TotalBsmtSF+X1stFlrSF+X2ndFlrSF+WoodDeckSF+OpenPorchSF+
                EnclosedPorch+X3SsnPorch+ScreenPorch+PoolArea+MiscVal,data=trainGroup)
summary(linearRegression.lm)
```